# Generated by Django 4.1 on 2022-08-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('matkul_id', models.IntegerField(primary_key=True, serialize=False)),
                ('matkul_name', models.TextField(max_length=100)),
                ('nama_dosen', models.TextField(max_length=100)),
                ('jumlah_sks', models.IntegerField()),
                ('ruangan', models.TextField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
