# Generated by Django 4.1 on 2022-08-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id_accordion', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
