# Generated by Django 4.1 on 2022-08-27 04:38

from django.db import migrations, models
import utils.helper


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=utils.helper.randomFileName('books')),
        ),
    ]
