# Generated by Django 4.1 on 2022-09-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_id_book_reference_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id_book_reference',
            field=models.TextField(unique=True),
        ),
    ]
