# Generated by Django 4.1 on 2022-08-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id_experience', models.AutoField(primary_key=True, serialize=False)),
                ('experience_type', models.TextField()),
                ('experience_name', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
