# Generated by Django 4.1 on 2022-08-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience_name',
        ),
    ]
