# Generated by Django 4.1 on 2022-09-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_rename_experience_type_experience_experience_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience_type_id',
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_type',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExperienceType',
        ),
    ]
