# Generated by Django 4.1 on 2022-09-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_experiencetype_alter_experience_experience_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='experience_type',
            new_name='experience_type_id',
        ),
    ]
