# Generated by Django 4.1 on 2022-09-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_rename_experience_type_experience_experience_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='experience_type_id',
            new_name='experience_type',
        ),
        migrations.RenameField(
            model_name='experiencetype',
            old_name='experience_type_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='experiencetype',
            old_name='experience_name',
            new_name='name',
        ),
    ]
